site_name: Documentation Pipeline USD 2025
site_url: https://thomasescalle.github.io/Pipeline_USD_2025/#project-layout
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: slate
      primary: teal
      accent: purple 
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ThomasEscalle

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/ThomasEscalle"  target="_blank" rel="noopener">Thomas ESCALLE</a>