site_name: Documentation Pipeline USD 2025
repo_url: https://github.com/ThomasEscalle/Pipeline_USD_2025-2026_src
site_url: https://thomasescalle.github.io/Pipeline_USD_2025/#project-layout
nav:
  - Accueil: index.md
  - Démarrage: demarage.md
  - Départements:
    - Départements: departements.md
    - Modeling Low: departements/ModelingLow.md
    - Modeling High: departements/ModelingHigh.md
    - Rigging Low: departements/RiggingLow.md
    - Rigging High: departements/RiggingHigh.md
    - Surfacing: departements/Surfacing.md
    - Modules: departements/Modules.md
    - SetDress: departements/SetDress.md
    - Master Lighting: departements/MasterLighting.md
    - RLO : departements/RLO.md
    - FLO: departements/FLO.md
    - Animation: departements/Anim.md
    - Assembly: departements/Assembly.md
    - Lighting: departements/Lighting.md
    - TLO: departements/TLO.md
    - Compositing: departements/Compositing.md
    - Matte Painting: departements/MattePainting.md
  - Structure: structure.md
  - Outils:
    - Outils: outils.md
    - Prism Pluggin Principal: outils/prism_main_pluggin.md
    - Maya "Shelf": outils/maya_shelf.md
    - Maya "Save As" Script: outils/maya_saveas_script.md
    - Installer: outils/installer.md
  - Q & A: qanda.md
  - References: references.md
theme:
  name: material
  features:
    - navigation.footer
    - navigation.tabs
    - toc.integrate
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo 
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ThomasEscalle

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: |
  &copy; 2025 <a href="https://github.com/ThomasEscalle"  target="_blank" rel="noopener">Thomas ESCALLE</a>